add features/basis-setup
oleksii-zviezdin/team-project-ice-cream pull request #1
Opened 2022-12-22 13:18 UTC by world-wanderer

Створює файл _base.scss (базові стилі, бекграунд на body).
Створює файл _reset.scss (скидає базові налаштування).
Створює файл _variables.scss (змінні).
Створює файл _mixins.scss.
Створює файл _placehorder.scss.
Створює файл fonts.html (підключення шрифтів).

2022-12-22 23:52 UTC, oleksii-zviezdin requested changes

2022-12-22 23:52 UTC, oleksii-zviezdin commented on src/sass/base/_reset.scss
> +.link {
.link => a

2022-12-22 23:52 UTC, oleksii-zviezdin commented on src/sass/base/_reset.scss
> +.list {
.list => ul

2022-12-22 23:52 UTC, oleksii-zviezdin commented on src/sass/base/_reset.scss
> +img {
перекинуть на base

2022-12-22 23:52 UTC, oleksii-zviezdin commented on src/sass/base/_base.scss
> +body {
Зробити ретіна на body для bg-img 

за прикладом в конспекті


/* Базові стилі і 1x зображення */
.box {
  width: 480px;
  height: 320px;
  background-image: url('photo.png');
  background-size: 480px 320px;
}

/* Перевизначаємо шлях до 2x зображення,
    якщо щільність екрану мінімум 2 */
@media (min-device-pixel-ratio: 2),
  (min-resolution: 192dpi),
  (min-resolution: 2dppx) {
  .box {
    background-image: url('photo@2x.png');
  }
}

2022-12-22 23:52 UTC, oleksii-zviezdin commented on src/partials/modern-normalize.html
> +<link
delete цей html

2022-12-22 23:52 UTC, oleksii-zviezdin commented on src/partials/fonts.html
> +<link
delete цей html - я його підключу в head

2022-12-22 23:52 UTC, oleksii-zviezdin commented on src/sass/utils/_placeholder.scss
> +%is-hidden {
Замінити на

.active {
  opacity: 1;
  visibility: visible;
}

і перенести в _base.scss

2022-12-22 23:52 UTC, oleksii-zviezdin commented on src/sass/utils/_placeholder.scss
> +%backdrop {
Замінити на

.overlay {
  opacity: 0;
  visibility: hidden;

  position: fixed;
  top: 0;
  left: 0;

  width: 100%;
  height: 100%;

  background-color: rgba(0, 0, 0, 0.2);
  z-index: 20;
  transition: opacity 250ms var(--timing-function);

  overflow-y: scroll;
}

і перенести в _base.scss

2022-12-22 23:52 UTC, oleksii-zviezdin commented on src/sass/utils/_placeholder.scss
> +%modal {
Замінити на

.modal {
  opacity: 0;
  visibility: hidden;

  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 30;

  width: 280px;

  background-color: var(--secondary-text-cl);
  border: 2px solid var(--accent-bg-txt-cl);
  border-radius:  var(--border-radius);

  [@media](https://t.me/media) screen and (min-width: 768px) {
    width: 568px;
  }

  [@media](https://t.me/media) screen and (max-width: 310px) {
    width: calc(100% - 30px);
  }
}

2022-12-22 23:52 UTC, oleksii-zviezdin commented on src/sass/utils/_placeholder.scss
> +  @media screen and (max-width: 479px) {
видалити це медіаправило

2022-12-23 10:56 UTC, world-wanderer commented on src/sass/base/_reset.scss
> +.link {
Виправлено

2022-12-23 10:56 UTC, world-wanderer commented on src/sass/base/_reset.scss
> +.list {
виправлено

2022-12-23 10:56 UTC, world-wanderer commented on src/sass/base/_reset.scss
> +img {
виправлено

2022-12-23 10:56 UTC, world-wanderer commented on src/sass/base/_base.scss
> +body {
виправлено

2022-12-23 10:56 UTC, world-wanderer commented on src/partials/modern-normalize.html
> +<link
видалено

2022-12-23 10:56 UTC, world-wanderer commented on src/partials/fonts.html
> +<link
видалено

2022-12-23 10:56 UTC, world-wanderer commented on src/sass/utils/_placeholder.scss
> +%is-hidden {
виправлено

2022-12-23 10:57 UTC, world-wanderer commented on src/sass/utils/_placeholder.scss
> +%backdrop {
виправлено

2022-12-23 10:57 UTC, world-wanderer commented on src/sass/utils/_placeholder.scss
> +%modal {
виправлено

2022-12-23 10:57 UTC, world-wanderer commented on src/sass/utils/_placeholder.scss
> +  @media screen and (max-width: 479px) {
виправлено

2022-12-23 11:51 UTC, oleksii-zviezdin requested changes

2022-12-23 11:51 UTC, oleksii-zviezdin commented on src/sass/index.scss
>  @import './example';
@import './example';
видали будь ласка ще цей рядок

2022-12-23 11:51 UTC, oleksii-zviezdin commented on src/index.html
>      <include src="./partials/example.html"></include>
<include src="./partials/example.html"></include>
видали будь ласка ще цей рядок теж

2022-12-23 12:00 UTC, world-wanderer commented on src/index.html
>      <include src="./partials/example.html"></include>
видалила

2022-12-23 12:01 UTC, oleksii-zviezdin approved these changes

2022-12-23 12:01 UTC, world-wanderer commented on src/sass/index.scss
>  @import './example';
видалила

2022-12-23 12:03 UTC, merged